apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ow2j
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ow2j
    app.kubernetes.io/part-of: cin4s-839-0038-app
  name: devfile-sample-ow2j
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ow2j
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ow2j
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0038-tenant/cin4s-839-0038-app/devfile-sample-ow2j@sha256:588ba3592782437b2e2fa5189623a6f7f1b237bbea69df059e54683f137c24dd
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
